apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dpg-ui.fullname" . }}-runtime
  labels:
    {{- include "dpg-ui.labels" . | nindent 4 }}
data:
  config.js: |
    window.__DPG_UI_CONFIG__ = {{ .Values.runtimeConfig | toJson }};
